### ISSUE TITLE
Import fails due to (non existing) duplicate element

### ISSUE THREAD

**Issue by tobiaskloss** [e-Spirit/FSDevTools#23]
### Summary
When importing content using the FSDevTools the import crashes due to duplicate elements. There is no duplicate element in existence though.

### Error
```
ERROR Import operation not successful
de.espirit.firstspirit.store.access.nexport.exceptions.SyncOperationException: [ExternalSync - Import] failed: Duplicate element id 3998632959672668959 detected: SiteStore/a/b/c/d/pagefolder_name SiteStore/a/b/c/pagefolder_name
	at de.espirit.firstspirit.store.access.nexport.operations.ImportOperationImpl.perform(ImportOperationImpl.java:133)
	at com.espirit.moddev.cli.commands.ImportCommand.call(ImportCommand.java:113)
	at com.espirit.moddev.cli.commands.ImportCommand.call(ImportCommand.java:49)
	at com.espirit.moddev.cli.Cli.executeCommand(Cli.java:221)
	at com.espirit.moddev.cli.Cli.execute(Cli.java:132)
	at com.espirit.moddev.cli.Cli.main(Cli.java:105)
Caused by: java.lang.IllegalStateException: Duplicate element id 3998632959672668959 detected: SiteStore/a/b/c/pagefolder_name SiteStore/a/b/c/d/pagefolder_name
	at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1518)
	at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1531)
	at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1531)
	at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1531)
	at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1531)
	at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1531)
	at de.espirit.firstspirit.store.access.nexport.ElementFileSystemSync.refresh(ElementFileSystemSync.java:134)
	at de.espirit.firstspirit.store.access.nexport.ElementFileSystemSync.getRootImportElements(ElementFileSystemSync.java:170)
	at de.espirit.firstspirit.store.access.nexport.operations.ImportOperationImpl.perform(ImportOperationImpl.java:126)
	... 5 more
```
### Conditions
_Element names have been anonymized_

The **Pagefolder** (1) `SiteStore/a/b/c/d/pagefolder_name` does exist in the source and in the target project.

The **Pagefolder** (2) `SiteStore/a/b/c/pagefolder_name` does not exist in the source nor in the target project.

The **Pagefolder** (1) was initially created as (2) but has been moved to (1) in 2017.

There is no deleted Element `SiteStore/a/b/c/pagefolder_name` in the source nor the target project.

Target project is an ~2 week old export of the source project.

**Comment by hannespernpeintner** [comment]
Hi Tobias, this seems to be a project situation or a product bug that is better handled by our technical support than here. Could you please file a ticket for that?

Thank you,
Hannes
