### ISSUE TITLE
ERROR Exception occurred during context initialization or command execution java.io.IOException: Underlying input stream returned zero bytes

### ISSUE THREAD

**Issue by frankbaus** [e-Spirit/FSDevTools#47]
Firstspirit Version 2020-10
FS-CLI Version: 2.6.2 / 2.6.10

We're seeing this error while importing/exporting templates.

```
Changing Path to /opt/fs-cli
 INFO fs-cli version 2.6.2 / git hash 360dcd5282cc7e4ff2af9a9c50cfcb7b0b8cd63b
 INFO Build for FirstSpirit version 5.2.200807
 INFO Using FirstSpirit Access API version 5.2.201107.79400 (fs-access.jar)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.espirit.moddev.cli.reflection.ReflectionUtils (file:/opt/fs-cli/lib/fsdevtools-cli-2.6.2.jar) to field sun.reflect.annotation.AnnotationInvocationHandler.memberValues
WARNING: Please consider reporting this to the maintainers of com.espirit.moddev.cli.reflection.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 INFO Executing ImportCommand
 INFO Connected to FirstSpirit server at localhost:8080 of version 5.2.201107.79400 (ISOLATED)
 INFO project is 'xxx'
 INFO Importing...
 INFO importing from directory '/fs-cli-data'
 INFO using the following temporary directory: /tmp
 INFO PAGESTORE(false) loaded in 966ms
 INFO CONTENTSTORE(false) loaded in 70ms
 INFO MEDIASTORE(false) loaded in 26ms
 INFO SITESTORE(false) loaded in 107ms
 INFO TEMPLATESTORE(false) loaded in 500ms
 INFO GLOBALSTORE(false) loaded in 26ms
ERROR Import operation not successful
java.io.IOException: Underlying input stream returned zero bytes
        at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.base/java.io.InputStreamReader.read(Unknown Source)
        at java.base/java.io.BufferedReader.fill(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at de.espirit.firstspirit.store.access.nexport.importer.ReferencesImporter.addLines(ReferencesImporter.java:100)
        at de.espirit.firstspirit.store.access.nexport.importer.ReferencesImporter.sourceInit(ReferencesImporter.java:66)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1543)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ElementFileSystemSync.refresh(ElementFileSystemSync.java:134)
        at de.espirit.firstspirit.store.access.nexport.ElementFileSystemSync.getRootImportElements(ElementFileSystemSync.java:170)
        at de.espirit.firstspirit.store.access.nexport.operations.ImportOperationImpl.perform(ImportOperationImpl.java:127)
        at com.espirit.moddev.cli.commands.ImportCommand.call(ImportCommand.java:121)
        at com.espirit.moddev.cli.commands.ImportCommand.call(ImportCommand.java:47)
        at com.espirit.moddev.cli.Cli.executeCommand(Cli.java:206)
        at com.espirit.moddev.cli.Cli.execute(Cli.java:129)
        at com.espirit.moddev.cli.Cli.main(Cli.java:102)
        at com.espirit.moddev.cli.Main.main(Main.java:11)
ERROR Exception occurred during context initialization or command execution
java.io.IOException: Underlying input stream returned zero bytes
        at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.base/java.io.InputStreamReader.read(Unknown Source)
        at java.base/java.io.BufferedReader.fill(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at de.espirit.firstspirit.store.access.nexport.importer.ReferencesImporter.addLines(ReferencesImporter.java:100)
        at de.espirit.firstspirit.store.access.nexport.importer.ReferencesImporter.sourceInit(ReferencesImporter.java:66)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1543)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ExportUtil.initImportElement(ExportUtil.java:1570)
        at de.espirit.firstspirit.store.access.nexport.ElementFileSystemSync.refresh(ElementFileSystemSync.java:134)
        at de.espirit.firstspirit.store.access.nexport.ElementFileSystemSync.getRootImportElements(ElementFileSystemSync.java:170)
        at de.espirit.firstspirit.store.access.nexport.operations.ImportOperationImpl.perform(ImportOperationImpl.java:127)
        at com.espirit.moddev.cli.commands.ImportCommand.call(ImportCommand.java:121)
        at com.espirit.moddev.cli.commands.ImportCommand.call(ImportCommand.java:47)
        at com.espirit.moddev.cli.Cli.executeCommand(Cli.java:206)
        at com.espirit.moddev.cli.Cli.execute(Cli.java:129)
        at com.espirit.moddev.cli.Cli.main(Cli.java:102)
        at com.espirit.moddev.cli.Main.main(Main.java:11)
 INFO Connection to FirstSpirit closed!
 INFO Execution time: 164.62s
```

I can't find any other logs to specify the error. Can you provide any info on this matter?

**Comment by cr4igo** [comment]
Hi Frank,

your version of fs-access-api jar is

INFO Using FirstSpirit Access API version **5.2.201107.79400** (fs-access.jar)

while as you stated your FirstSpirit Server Version is **2020-10**.
Those have to match exactly. So after an FirstSpirit upgrade, you have also to upgrade all the fs-access/isolated-runtime jars.

This byte-thing errors just come from the FirstSpirit-Servlet, which then has a different format and so on.
Put the 2020-10 fs-access.jar or fs-isolated-runtime.jar into the ./lib folder of the fs-cli, then it will work.

Best regards,
Markus

**Comment by frankbaus** [comment]
Hi Markus, 

sorry, my bad about the version. We're indeed using 2020.11. It seems like the issue is down to one of our Media Files (most likely a SVG). 
It would just be nice, if the error reflected that.

Thanks for your help!

Frank
